# Separar data y crear carpetas

In [18]:
import glob
import shutil
import os

import pandas as pd
import numpy as np
SEED=43

In [19]:
df = pd.read_csv('Clase_SUV.csv')
df = df.iloc[:,[1,2]]
df

         Imagen  Dummy
0     00001.jpg      0
1     00002.jpg      0
2     00003.jpg      0
3     00004.jpg      0
4     00005.jpg      0
...         ...    ...
8139  08140.jpg      0
8140  08141.jpg      0
8141  08142.jpg      0
8142  08143.jpg      0
8143  08144.jpg      0

[8144 rows x 2 columns]

In [34]:
X, y = df.iloc[:, 0:1], df.iloc[:, [1]]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=SEED)

## Para SUV
# TEST 20%
y_test_SUV = y_test[y_test["Dummy"]==1]
X_test1_SUV = X_test[y_test["Dummy"]==1]

# TRAIN 80%
y_train1_SUV = y_train[y_train["Dummy"]==1]
X_train1_SUV = X_train[y_train["Dummy"]==1]

## Para NO SUV
# TEST 20%
y_test1_NOSUV = y_test[y_test["Dummy"]==0]
X_test1_NOSUV = X_test[y_test["Dummy"]==0]

# TRAIN 80%
y_train1_NOSUV = y_train[y_train["Dummy"]==0]
X_train1_NOSUV = X_train[y_train["Dummy"]==0]

In [35]:
X_test1_SUV

         Imagen
5283  05284.jpg
5032  05033.jpg
7010  07011.jpg
3125  03126.jpg
2034  02035.jpg
...         ...
8102  08103.jpg
7286  07287.jpg
3259  03260.jpg
6641  06642.jpg
2959  02960.jpg

[311 rows x 1 columns]

In [36]:
#1
files0 = X_test1_SUV['Imagen']

# Hay que crear una carpeta vacia que se llame dest_folder

for f in files0:
    shutil.copy(f, 'SUV_test')

In [37]:
#2
files0 = X_train1_SUV['Imagen']

# Hay que crear una carpeta vacia que se llame dest_folder

for f in files0:
    shutil.copy(f, 'SUV_train')

In [38]:
#3
files0 = X_test1_NOSUV['Imagen']

# Hay que crear una carpeta vacia que se llame dest_folder

for f in files0:
    shutil.copy(f, 'NO_SUV_test')

In [39]:
#4
files0 = X_train1_NOSUV['Imagen']

# Hay que crear una carpeta vacia que se llame dest_folder

for f in files0:
    shutil.copy(f, 'NO_SUV_train')